name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Ilmen
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - name: Check types and style
        run: npm run check
      - name: Test
        run: npm test
      - name: Ensure Quartz builds, check bundle info
        run: npx quartz build --bundleInfo

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: superdaminou
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/superdaminou/ilmen:latest

      - name: Restarting server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose -f ./app/docker-compose.yaml down
            docker compose -f ./app/docker-compose.yaml up -d
